name: "eamxx-format"

# if .{cpp,hpp} files are touched in a PR, lint them!

on:
  pull_request:
    branches: ["master"]
    paths:
      - 'components/eamxx/**/*.cpp'
      - 'components/eamxx/**/*.hpp'

  # Manual run
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  clang-format-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: tj-actions/changed-files@v46
      id: changed-files
      with:
        files: 'components/eamxx/**/*.{cpp,hpp}'
        separator: " "
    - name: create conda env
      run: |
        conda create -n clang-format
        conda activate clang-format
        conda install clang-format
    - name: run formatter looping over PR-changed files, then diff -  PR trigger
      # Note: this (json) variable contains a handful of sub-fields, but its
      # existence encapsulates all of the PR-related triggers
      # this is the best option because github.event_name could be something
      # like "synchronization," which falls under the umbrella of PR triggers
      if: ${{ github.event.pull_request }}
      run: |
        conda activate clang-format
        flist="${{ steps.changed-files.outputs.all_changed_files }}"
        run_cfmt () {
          clang-format-18 -i --style=file:"components/eamxx/.clang-format" $1
        }
        for f in ${flist[@]}; do
          echo "--Running clang-format on ${f}--"
          run_cfmt "${f}"
        done
        git diff --name-only > diffiles.txt
    - name: run formatter looping over all files, then diff - manual trigger
      # Note: different from above, this trigger does not result in a variable
      # github.event.workflow_dispatch, but this will always be the event_name
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        conda activate clang-format
        # when it's a manual trigger, we'll choose to consider all cpp/hpp files
        flist=($(find components/eamxx -depth -name "*.*pp"))
        run_cfmt () {
          clang-format-18 -i --style=file:"components/eamxx/.clang-format" $1
        }
        for f in ${flist[@]}; do
          echo "--Running clang-format on ${f}--"
          run_cfmt "${f}"
        done
        git diff --name-only > diffiles.txt
    - name: examine diff and write to summary
      run: |
        if [[ $(wc -l < diffiles.txt) -gt 0 ]]; then
          # we don't want to return a nonzero exit code in this step because
          # it'll stop the job, so we store it in the ENV
          echo "status_fail=true" >> "${GITHUB_ENV}"
          echo "## Status: \`clang-format\` Check Failed." > "${GITHUB_STEP_SUMMARY}"
          echo "" >> "${GITHUB_STEP_SUMMARY}"
          echo "The following files require formatting:" >> "${GITHUB_STEP_SUMMARY}"
          echo "" >> "${GITHUB_STEP_SUMMARY}"
          echo "\`\`\`" >> "${GITHUB_STEP_SUMMARY}"
          cat diffiles.txt >> "${GITHUB_STEP_SUMMARY}"
          echo "\`\`\`" >> "${GITHUB_STEP_SUMMARY}"
          echo "" >> "${GITHUB_STEP_SUMMARY}"
          echo "To format all of these files at once, download the " \
               "patch file below, \`clang-format-patch_[...].diff\`, " \
               "from the ***Artifacts*** section." >> "${GITHUB_STEP_SUMMARY}"
          echo "Note that it may take a moment for the file to appear " \
               "or may require reloading the page." >> "${GITHUB_STEP_SUMMARY}"
          echo "" >> "${GITHUB_STEP_SUMMARY}"
          echo "To apply the patch containing the formatting edits, " \
               "execute \`git apply <patch-file>\` from your local E3SM " \
               "branch." >> "${GITHUB_STEP_SUMMARY}"
          echo "Then commit the changes and push to your remote branch." >> "${GITHUB_STEP_SUMMARY}"
        else
          echo "status_fail=false" >> "${GITHUB_ENV}"
          echo "## Status: \`clang-format\` Check Passed!" > "${GITHUB_STEP_SUMMARY}"
        fi
    - name: diff format changes
      run: git diff > "components/eamxx/clang-format-patch.diff"
    - name: upload diff patch
      if: ${{ env.status_fail == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: clang-format-patch_${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.run_id }}.diff
        path: |
          components/eamxx/clang-format-patch.diff
    - name: return pass-fail status
      run: |
        if [[ ${status_fail} = true ]]; then
          exit 1
        else
          exit 0
        fi
