name: hommexx-unit-tests

on:
  # Runs on PRs against master
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, ready_for_review, reopened]
    paths:
      - '.github/workflows/hommexx-unit-tests.yml'
      - 'components/homme/**'

  # Manual run is used to bless
  workflow_dispatch:

  # Also run nightly
  schedule:
    - cron: '0 7 * * *'  # Runs at 7 AM UTC, which is midnight MT during Standard Time

concurrency:
  # Two runs are in the same group if they are testing the same git ref
  #  - if trigger=pull_request, the ref is refs/pull/<PR_NUMBER>/merge
  #  - for other triggers, the ref is the branch tested
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cpu-gcc:
    runs-on:  [ubuntu-latest]
    name: cpu-gcc
    steps:
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9  # Specify your desired Python version
          channels: conda-forge,defaults  # Specify your desired channels
          auto-activate-base: false
          activate-environment: homme-env
      - name: Install conda packages
        shell: bash -l {0}  # Use bash -l to ensure conda commands are available
        run: |
          conda install -c conda-forge                  \
            gcc=13.2.0 gxx=13.2.0 gfortran=13.2.0 cmake \
            openmpi openblas
      - name: Check out the repository
        uses: actions/checkout@v5
        with:
          path: e3sm/source
      - name: Show action trigger
        uses: ./e3sm/source/.github/actions/show-workflow-trigger
      - name: get submodules
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          cd ${GITHUB_WORKSPACE}/e3sm/source
          git submodule update --init --recursive cime
          git submodule update --init externals/ekat
          cd externals/ekat
          git submodule update --init extern/kokkos
          git submodule update --init extern/Catch2
      - name: hommexx-configure
        shell: bash -l {0}  # Use bash -l to ensure conda commands are available
        run: |
          cd ${GITHUB_WORKSPACE}/e3sm
          mkdir build && cd build
          cmake \
           -D CMAKE_CXX_COMPILER:STRING=mpicxx        \
           -D CMAKE_C_COMPILER:STIRNG=mpicc           \
           -D CMAKE_Fortran_COMPILER:STRING=mpifort   \
           -D CMAKE_BUILD_TYPE:STRING=DEBUG           \
           \
           -D HOMME_FIND_BLASLAPACK:BOOL=ON           \
           -D HOMMEXX_BFB_TESTING:BOOL=ON             \
           -D BUILD_HOMME_WITHOUT_PIOLIBRARY:BOOL=ON  \
           \
           -S ${GITHUB_WORKSPACE}/e3sm/source/components/homme
      - name: hommexx-build
        shell: bash -l {0}  # Use bash -l to ensure conda commands are available
        run: |
          cd ${GITHUB_WORKSPACE}/e3sm/build
          make -j4
      - name: hommexx-test
        shell: bash -l {0}  # Use bash -l to ensure conda commands are available
        run: |
          cd ${GITHUB_WORKSPACE}/e3sm/build
          ctest --output-on-failure -L unit
      - name: Upload log files
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            e3sm/build/CMakeCache.txt
            e3sm/build/Testing/Temporary/Last*
          retention-days: 14
